version: 2
jobs:
  build:
    docker:
      - image: thegreenhouse/nodejs-dev:0.2.0

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install Project Dependencies
          command: yarn install

      - run:
          name: Execute The Build
          command: |
            if [ "${CIRCLE_BRANCH}" == "develop" ]; then
              
              echo "develop branch, releasing to stage (AWS)"
              yarn run build
              yarn run release:stage

            elif [ "${CIRCLE_BRANCH}" == "develop" ]; then

              echo "master branch, nothing to do since process is manual"
              yarn run build

            else

              echo "Branch undetermined, likely a CI build"
              yarn run build
            
            fi