name: Deploy GitHub Pages

on:
  push:	
    branches:	
      - develop

jobs:

  build-and-deploy:
    runs-on: ubuntu-18.04
    container: docker://thegreenhouse/nodejs-dev:0.4.0
  
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v2
      env:
        ACCESS_TOKEN: ${{ secrets.GITHUB_PAGES }}
        BASE_BRANCH: develop # The branch the action should deploy from.
        BRANCH: master # The branch the action should deploy to.
        FOLDER: public # The folder the action should deploy.
        BUILD_SCRIPT: yarn install && yarn build # The build script the action should run prior to deploying.