name: Deploy GitHub Pages

on:
  push:
    branches:
      - master

jobs:

  build-and-deploy:
    runs-on: ubuntu-18.04
    container: docker://thegreenhouse/nodejs-dev:0.4.0
  
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Yarn install
      run: |
        yarn install --frozen-lockfile

    - name: Yarn Build
      run: |
        yarn lint && yarn build

    # - name: Build and Deploy
    #   uses: JamesIves/github-pages-deploy-action@releases/v2
    #   env:
    #     ACCESS_TOKEN: ${{ secrets.GITHUB_PAGES }}
    #     BASE_BRANCH: master # The branch the action should deploy from.
    #     BRANCH: master # The branch the action should deploy to.
    #     FOLDER: docs # The folder the action should deploy.
    #     BUILD_SCRIPT: yarn install && yarn build && yarn pages # The build script the action should run prior to deploying.